### PR TITLE
Add live preview url to docs lander

### PR DESCRIPTION
**Pull request by kale-stew**
### Description

We weren't using some keys in _content so I got rid of them (unless someone objects) - I don't see us using them in the near future anyway?

I think it would be handy for the live preview to click through to the real live preview.

#### Type of Change

- [X] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by kale-stew** [comment]
CI fails over the surge login, not really sure why 🤔

**Comment by ryan-roemer** [comment]
Surge failure is:

```
[deploy/surge] Uploading files to formidable-com-spectacle-staging-860.surge.sh
   Invalid token
```

which doesn't seem quite right (e.g., nothing in this PR would affect it).

Rebuilding just the Travis doc task to see if we get a successful deploy.

**Comment by ryan-roemer** [comment]
Surge token locally appears invalid too. I've update 1password with the current token from `surge token` after a login and updated here in this PR in encrypted travis secrets. 🤞

**Comment by ryan-roemer** [comment]
After new token, deploy went through. Weird:

```
$ node scripts/deploy/surge.js
[deploy/surge] Uploading files to formidable-com-spectacle-staging-860.surge.sh
   Running as [secure] (Student)
        project: /home/travis/build/FormidableLabs/spectacle/docs/dist
         domain: formidable-com-spectacle-staging-860.surge.sh
             IP: 45.55.110.124
   Success! - Published to formidable-com-spectacle-staging-860.surge.sh
```

**Pull request merged**
