### PR TITLE
add missing semicolon

### PR DESCRIPTION
**Pull request by ami44**
if windows, "npm start" fail !

```

ERROR in ./src/components/spectacle.js
Module build failed: SyntaxError: C:/ami44/spectacle/src/components/spectacle.js: A semicolon is required after a class property (14:3)
  12 |     children: PropTypes.node,
  13 |     theme: PropTypes.object
> 14 |   }
     |    ^
  15 |
  16 |   render() {
  17 |     return (
    at Parser.pp.raise (C:\ami44\spectacle\node_modules\babel-core\node_modules\babylon\index.js:1413:13)
    at Parser.pp.parseClassProperty (C:\ami44\spectacle\node_modules\babel-core\node_modules\babylon\index.js:2565:10)
    at Parser.<anonymous> (C:\ami44\spectacle\node_modules\babel-core\node_modules\babylon\index.js:3774:20)
    at Parser.parseClassProperty (C:\ami44\spectacle\node_modules\babel-core\node_modules\babylon\index.js:3774:20)
    at Parser.pp.parseClassBody (C:\ami44\spectacle\node_modules\babel-core\node_modules\babylon\index.js:2470:34)
    at Parser.pp.parseClass (C:\ami44\spectacle\node_modules\babel-core\node_modules\babylon\index.js:2413:8)
    at Parser.pp.parseExport (C:\ami44\spectacle\node_modules\babel-core\node_modules\babylon\index.js:2630:19)
    at Parser.<anonymous> (C:\ami44\spectacle\node_modules\babel-core\node_modules\babylon\index.js:3625:20)
    at Parser.parseExport (C:\ami44\spectacle\node_modules\babel-core\node_modules\babylon\index.js:3625:20)
    at Parser.pp.parseStatement (C:\ami44\spectacle\node_modules\babel-core\node_modules\babylon\index.js:1916:90)
 @ ./src/index.js 80:17-50
```

### CODE REVIEW

**Comment by ami44** [comment]
Update also README.markdown because link http://localhost:3000/#/?presenter not work on windows.

**Comment by pedrottimark** [comment]
Babel had previously overlooked the missing semicolon, but 6.4.0 has made it a parsing error.
https://phabricator.babeljs.io/T6873

**Comment by knowbody** [comment]
@ami44 looks good to me, thank you. Could you squash your commits, please?

**Comment by ami44** [comment]
Why not, but can you before update package.json to set "babel-core" with a correct version (see @pedrottimark comment) 

Can you also update README.markdow like https://github.com/FormidableLabs/spectacle/pull/142/files

Or accept this pullrequest :-)

Ami44

**Comment by knowbody** [comment]
I'm AFK, mind adding those here and squashing. Or i can have a look at it in a few hours 

-----
Best,
Matt




On Sat, Jan 9, 2016 at 6:34 AM -0800, "ami44" <notifications@github.com> wrote:












Why not, but can you before update package.json to set "babel-core" with a correct version (see @pedrottimark comment) 



Can you also update README.markdow like https://github.com/FormidableLabs/spectacle/pull/142/files



Or accept this pullrequest :-)



Ami44

**Pull request closed without merging**
