### PR TITLE
Fixes #539

### LINKED ISSUE #539: Using insecure websockets prevents deployment with https.
## Expected Behavior
Building and deploying the build folder should result in a site that presents content without being blocked by modern browsers.

## Actual Behavior
Using the ws:// protocol instead of the wss://protocol makes it so the browser blocks the entire content of the page.

### Initial Page Load
initial-page-load

### Before "Loading Unsafe Scripts"
before-permitting-scripts

### After "Loading Unsafe Scripts"
after-permitting-scripts

## Steps to Reproduce the Problem
  1. Install with the CRA workflow `create-react-app my-presentation --scripts-version spectacle-scripts`
  1. Run `yarn build` or `npm run build`
  1. Deploy the build folder using now or surge or GitHub pages i.e. `cd build && now --static`
  1. Open the deployment in Chrome and view the blocked script indicator on the right hand side of the URL bar.

## Fixing the problem
I fixed the problem by digging through the node_modules folder and changing every instance of ws:// to wss:// and it worked perfectly. I'd be happy to make a PR if someone with more experience with sockets can chime in with any potential issues.

## Specifications
  - Version: spectacle-scripts: "2.0.0"
  - Platform: Firefox developer edition, Chrome 66

### PR DESCRIPTION
**Pull request by vpicone**
Use secure web socket protocol.

### CODE REVIEW

**Comment by ryan-roemer** [comment]
@vpicone -- I've just merged in a massive (but superficial) PR actually applying prettier to all our files, which produces a merge conflict here. Can you rebase / merge in current `master` to catch up here?

Thanks! We've got folks who will be verifying this after that...

**Comment by vpicone** [comment]
@ryan-roemer done!

**Comment by vpicone** [comment]
@ryan-roemer  Is this CI build broken? Not sure why this would fail.

**Comment by ryan-roemer** [comment]
CI broke because prettier is unhappy. Our postcommit hooks _should_ have fixed things per prettier's demands, so if we can diagnose why that didn't happen here, I'm very interested.

But to move us along here, just run:

```
$ yarn run prettier-fix
```

and commit the result.

**Comment by ryan-roemer** [comment]
We decided to revert the WS stuff in https://rawgit.com/FormidableLabs/spectacle/master/one-page.html instead, so closing here. Thanks so much for the quick stab at fixing things!

**Pull request closed without merging**
