### PR TITLE
Task use prop types

### PR DESCRIPTION
**Pull request by stefvhuynh**
Swap out `React.PropTypes` with `PropTypes`.

### CODE REVIEW

**Comment by exogen** [comment]
Looks like tests are alread yfailing in `master` even without this.

**Comment by stefvhuynh** [comment]
@exogen, the unit tests are passing on my machine on master and on this branch.

**Comment by exogen** [comment]
That's weird, the snapshot tests involving SVG values fail locally for me. Looks like the CI failure here is not that, though, just a timeout?

**Comment by exogen** [comment]
Now tracking in #307 and #306.

**Comment by stefvhuynh** [comment]
yeah, it looks the CI failure is the timeout on several PRs here.

**Comment by kenwheeler** [comment]
LGTM

**Comment by stefvhuynh** [comment]
@kenwheeler, should we merge this even with the CI failure?

**Comment by kenwheeler** [comment]
Yeah, its a 5 problem, not a PR problem

**Comment by exogen** [comment]
@stefvhuynh If you rebase/merge `master`, CI should be fixed.

**Pull request merged**
