### PR TITLE
Default theme: add maxWidth to image and make pacman responsive

### PR DESCRIPTION
**Pull request by sw-yx**
hi! as per twitter discussion with Phil Pluckthun: <https://twitter.com/swyx/status/938542083647901696>

wanted to get the discussion going on making the default theme a little more mobile friendly.

### CODE REVIEW

**Comment by kenwheeler** [comment]
Hey, gave this a shot locally and had some issues with sizing and alignment. Further, I think we should chat about how it should work in mobile. Should the dots stack? Perhaps we should default to the progress bar for smaller screens?

**Comment by sw-yx** [comment]
I think thats a discussion thats best done with the maintainers as I'm kind of a drive-by user of Spectacle right now and you guys have the long term vision. I do think the small screen progress bar default makes sense, would be friendly for longish presentations without compromising on the desktop experience.

**Comment by kale-stew** [comment]
Closing as outdated, but thank you for the contribution @sw-yx! We are rewriting the library and will be handling themes/sizing/pretty much everything a little differently, please keep an eye out for v6. 🙂

**Comment by sw-yx** [comment]
My disappointment is immeasurable, and my day is ruined

**Comment by kale-stew** [comment]
😭

**Pull request closed without merging**
