### PR TITLE
Fixes example paths

### PR DESCRIPTION
**Pull request by bmathews**
This fixes the broken paths so that `npm start` and the example presentation works. 

/cc @ebrillhart

### CODE REVIEW

**Comment by bebraw** [comment]
On a related note, it might be nice if you had a regression test in place (stats/stop server on Travis or something like that) to avoid this kind of breakage in the future.

**Comment by ebrillhart** [comment]
@bmathews how did I just see this. thank you!! I should be easily able to pull in the example to spectacle-docs now and set it up to run at open-source/spectacle/example?

**Comment by bmathews** [comment]
@ebrillhart If the docs have all the proper webpack loaders, yeah.

https://github.com/FormidableLabs/spectacle/blob/master/webpack.config.js#L40-L58

**Comment by ebrillhart** [comment]
@bmathews has this been npm published yet?

**Comment by bmathews** [comment]
Nope

**Comment by ebrillhart** [comment]
@bmathews welp. yeah. duh. hasn't even been merged yet. do you want to merge it?

**Pull request merged**
