### PR TITLE
show progress in a funny way (fix #9)

### LINKED ISSUE #9: Add a progress bar
Optional, of course

### PR DESCRIPTION
**Pull request by mathieudutour**
I worked on a presentation and wanted to share with you guys the way i'm showing the progress. 
Cheers

### CODE REVIEW

**Comment by mathieudutour** [comment]
btw, all the warnings come from here : https://github.com/FormidableLabs/radium/issues/232

**Comment by kenwheeler** [comment]
Awesome , I'll run it and check it out when I get home. Been meaning to add a progress element.

**Comment by kenwheeler** [comment]
Finally ran this, and you just blew my mind. Most creative thing I've seen in like a month!

**Comment by mathieudutour** [comment]
Thanks!

**Comment by kenwheeler** [comment]
I'm kind of wary to include pac man as a lib default, but if you want to make it a bar across the bottom, I'll gladly merge into core

**Comment by mathieudutour** [comment]
Done. There is 4 different options now: `pacman`, `bar`, `number` and `none`.

**Comment by kenwheeler** [comment]
amazing

**Comment by luisrudge** [comment]
:+1:

**Comment by kenwheeler** [comment]
Code looks fantastic, once I get to test across browsers, merging. Thank you so much.

**Comment by kenwheeler** [comment]
This is downright perfect. Looks amazing everywhere. Only thing is, can we change `showProgress` to just progress and should the bar version start with bar showing, or should it be width: 0 for the first slide?

**Comment by kenwheeler** [comment]
@mathieudutour By the way, thanks again, you are killing it.

**Comment by mathieudutour** [comment]
done. thanks

**Comment by kenwheeler** [comment]
Boom!

**Pull request merged**
