### PR TITLE
feat(keyboardhook): add keyUd/keydown for next slide (#657)

### LINKED ISSUE #657: Feature request: Up/Down keyboard hook for next/back slide
### Description
I'd like to request for Up/Down keyboard hook to move the slide back and forth. I know what there are few clickers that only do up/down and it was really troublesome to use third party software to intercept key and map to left/right - that would affect the normal keyboard ket

### Proposal
I can do a PR if the request is approved :)

### PR DESCRIPTION
**Pull request by dkosasih**
Closes #657

#### Type of Change
Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

### How Has This Been Tested?
Added unit test (partially). #660 needed to be fixed before writing more cases

### CODE REVIEW

**Comment by dkosasih** [comment]
Hi @ebrillhart,

This is a draft pull request to investigate #660  before writting more test cases to fully complete #657 feature.

Thank you for having a look. :)

**Comment by kale-stew** [comment]
@dkosasih as I mentioned, I am taking over maintenance of Spectacle!

I have a couple of questions + one request for you:

  - Did you do a fresh `yarn` install when you created your branch? The 'unknown identifier' error you referenced seems reminiscent of missing node_modules errs I've run into in the past
  - What test is failing on your machine? I'm running into some outdated snapshots, but that's to be expected when you add a new prop to the Manager. Beyond that, everything is looking pretty good.
   - Could you please update the TypeScript defs in `index.d.ts` to include this Boolean prop on the Manager component?

**Comment by kale-stew** [comment]
Also, do I have your permission to mark this as "Ready for review" so we can start working on feedback? 🙂

**Comment by dkosasih** [comment]
Hey Kale,

Apologies for the late reply. 
yes, please do so. :)

**Comment by kale-stew** [comment]
We are about to roll out a rewritten version of the library, so I am going to close this for now and implement it in our future control feature work in v6 (aka ✨ New Spectacle ✨). Thank you for your contribution, @dkosasih, I do hope you check out v6 and consider contributing again in the future. 🙂

**Pull request closed without merging**
