### PR TITLE
Change prop from `style` to `styles` for table components

### PR DESCRIPTION
**Pull request by mpeyper**
When trying to use the base props to set the `textAlign` value of a `TableItem` component, I discovered that it was not working.  Investigating the issue, it seems that there was a missing 's' on the `styles` prop being passed through to the underlying emotion component.

I did a scan of the other components and found that `TableRow` and `TableHeader` were also not passing the correct prop through.

### CODE REVIEW

**Comment by tlenclos** [comment]
Yep, can't override style, can we merge this ?

**Comment by ebrillhart** [comment]
Hey @mpeyper! Sorry for the delay. I'm taking over as maintainer for the project and will review this and merge or give feedback within the week. Thanks!

**Comment by mpeyper** [comment]
I'll take a look later today

**Comment by mpeyper** [comment]
Hey @ebrillhart,

Sorry for the delay.  The PR is now up to date with master.

Have a good day 😃

**Pull request merged**
