### PR TITLE
Add autoplayLoop prop

### PR DESCRIPTION
**Pull request by nuragic**
Hi!

This PR add the possibility to set the autoplay loop from outside (defaults to `true` cause it's the current behavior, although I'd say that `false` should make more sense eventually). 

Any suggestion/feedback/whatever will be very welcome, thanks!

_P.S. tests were already failing before this commit so I'm not sure if that's ok or not_ 💭

### CODE REVIEW

**Comment by ryan-roemer** [comment]
Thanks for opening a PR!

I'll let @kenwheeler opine as to the substantive PR when he has a moment, but on the tests front `master` build is fully green, both in Travis [`master`](https://travis-ci.org/FormidableLabs/spectacle/builds/356600522) and on my local machine from a fresh install.

All of the failures I see for one of the travis builds here are for the `autoplay` stuff you've added failing because of mismatch with the fixtures -- https://travis-ci.org/FormidableLabs/spectacle/jobs/360482085 . I'm guessing a jest snapshot update is in order.

As a helpful tip, all code needs to pass:

```sh
$ yarn run build
$ yarn run check
```

... which is what travis is doing...

Thanks!

**Comment by ryan-roemer** [comment]
@nuragic -- Can you create a gist of the entire terminal log from a fresh `master` clone + `yarn install` (since we're using a yarn.lock). Then echo your `node -v` and `yarn -v` into the terminal, then run the tests. And paste that all in a gist so I can take a look. Thanks!

**Comment by nuragic** [comment]
@ryan-roemer Sorry, I removed my entire folder, cloned the fork again... and it worked 😅 ... wondering what could have originated the problem, anyway... nevermind! Thanks for your time, I've just updated the snapshots for this branch.

**Comment by ebrillhart** [comment]
Hey @nuragic, sorry for the delay - if you could fix the merge conflicts I'll accept this PR.

**Comment by nuragic** [comment]
Hi Emma! No worries... done! 🚢

**Comment by ebrillhart** [comment]
@nuragic ah sorry, it also looks like prettier is failing in CI, which is something we've added since you originally pushed this. If you could pull down, make sure you have latest master merged in/do a fresh yarn or npm install, and run `yarn prettier-fix`, that should solve the problem! Thanks for working with me on this.

**Comment by nuragic** [comment]
Upsss sorry 😅 fixed! Thanks to you for your time 🙌

**Pull request merged**
