### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Jawad-H**
### Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

#### Type of Change

Please delete options that are not relevant (including this descriptive text).

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

### Checklist: (Feel free to delete this section upon completion)

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My code follows the style guidelines of this project (I have run `yarn format`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes (I have run `yarn test`)
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Jawad-H** [comment]
meta viewport missing

**Review by gksander — APPROVED** [review]
Nice find, thank you!

**Comment by Jawad-H** [comment]
same missing here:
https://github.com/FormidableLabs/spectacle/blob/main/examples/js/index.html

**Comment by Jawad-H** [comment]
> Nice find, thank you!

same missing here too:
https://github.com/FormidableLabs/spectacle/blob/main/examples/js/index.html

**Review by Jawad-H — COMMENTED** [review]
thanku

**Comment by Jawad-H** [comment]
@gksander ok

**Pull request closed without merging**
