### PR TITLE
Feature/add bg lighten

### LINKED ISSUE #445: [FR] Add bgLighten config/prop
Add a prop to enable `bgLighten` like `bgDarken` for `bgImage`.

### PR DESCRIPTION
**Pull request by samwhale**
Fixes #445 
* Add bgLighten prop to base.js. Add bgLighten description to README.md
* Prettified README.md and src/utils/base.js
* Add console warning for bgLighten and bgDarken

### CODE REVIEW

**Comment by ryan-roemer** [comment]
Have these files (like the readme) been run through prettier? (We’ve got a lot of unrelated formatting changes — we can probably roll with it here for an otherwise small pr, but we typically like to keep prs focused on “just one thing”)

**Comment by sam-whale** [comment]
README.md was logging an error on commit. The file hadn't been through prettier yet. To commit and pass the tests, I ran prettier on README.md.

**Comment by ryan-roemer** [comment]
Thanks @sam-whale -- we'll fix this after this PR in https://github.com/FormidableLabs/spectacle/pull/532

**Comment by ebrillhart** [comment]
sorry @samwhale this got added in a larger PR so I am closing this one!

**Pull request closed without merging**
