### PR TITLE
Fix broken WS syncing.

### PR DESCRIPTION
**Pull request by ryan-roemer**
- Unwinds and removes websocket syncing from #495, going back to `localStorage`.
- Causes travis to fail on outdated / missing deps in `yarn.lock`.

/cc @kenwheeler @coopy @samwhale @zhaostan

### CODE REVIEW

**Comment by kitten** [comment]
Maybe a reimplementation of websocket-syncing would make more sense to be similar to: https://github.com/kitten/spectacle-sync, as in being a separate package?

**Comment by ryan-roemer** [comment]
@kitten -- Do we even need an implementation _in_ Spectacle or just some verbiage + a link to `spectacle-sync` in the README here?

**Comment by samwhale** [comment]
I'm not seeing 502 errors anymore. Just this: `Error during service worker registration: DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV)`. I think it's good to go.

**Comment by ryan-roemer** [comment]
Released in `spectacle@4.3.1`

**Pull request merged**
