### PR TITLE
Chore/adding types check

### LINKED ISSUE #1203: `website`: Add quality checks.
We need to add all the following to `website/package.json` wireit tasks:

- [x] `lint`
- [x] `lint:fix`
- [x] `prettier`
- [x] `prettier:fix`
- [ ] `types:check` (Note -- this is blocked by #1201 )

Then:

- [ ] Integrate all those checks in root aggregate tasks in `package.json`
- [ ] Remove `paths-ignore` in main CI workflow so we do all docs code checking there
- However, let's keep the `build` task in `website` out of both wireit and CI and leave it to just the docs workflow.

### PR DESCRIPTION
**Pull request by paulmarsicloud**
### Description

Changing `typecheck` in `website` to `types:check`
Removing `typescript` dev dependency from `website`
Adding `shamefully-hoist=true` to `.npmrc` in order for `types:check` to work from root. If `shamefully-hoist=false` (default setting [here](https://pnpm.io/npmrc#shamefully-hoist)) we we're getting [this error](https://github.com/FormidableLabs/spectacle/issues/1203#issuecomment-1226635980)

Fixes #1203 

#### Type of Change

Please delete options that are not relevant (including this descriptive text).

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

### Checklist: (Feel free to delete this section upon completion)

- [ ] I have included a [changeset](../CONTRIBUTING.md#changesets) if this change will require a version change to one of the packages.
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have run `pnpm run check:ci` and all checks pass
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by gksander** [comment]
@paulmarsicloud The whole `shamefully-hoist=true` thing makes me feel shame 😆 I just pulled this branch down, removed that line, nuked cache and re-installed stuff – and was able to run `pnpm run check:ci` and get everything passing on the first try.

Do you have any more details on how to reproduce the error you encountered that you needed the hoisting for? I feel like I'm probably missing something very obvious.

**Comment by ryan-roemer** [comment]
Let me try and experiment without `shamefully-hoist=true` and see what I can find.

**Comment by ryan-roemer** [comment]
@paulmarsicloud Here's a much more surgical hoisting allowance for the bad phantom dependency:

```diff
diff --git a/.npmrc b/.npmrc
index c67cd2d..519f90d 100644
--- a/.npmrc
+++ b/.npmrc
@@ -1,3 +1,5 @@
 strict-peer-dependencies=false
 prefer-workspace-packages=true
-shamefully-hoist=true
\ No newline at end of file
+
+# Docusaurus has some phantom dependencies, so specifically hoist those.
+public-hoist-pattern[]=@docusaurus/theme-classic
diff --git a/website/package.json b/website/package.json
index 81a1b08..926a5e4 100644
--- a/website/package.json
+++ b/website/package.json
@@ -12,8 +12,10 @@
     "@docusaurus/preset-classic": "^2.0.1",
     "@docusaurus/theme-live-codeblock": "^2.0.1",
     "@docusaurus/theme-search-algolia": "^2.0.1",
+    "@docusaurus/types": "^2.0.1",
     "@mdx-js/react": "^1.6.22",
     "@tsconfig/docusaurus": "^1.0.5",
+    "@types/node": "^18.0.3",
     "@types/styled-components": "^5.1.25",
     "clsx": "^1.1.1",
     "docusaurus-plugin-sass": "^0.2.2",
```

Want me to make a commit (alongside the pnpm-lock.yaml changes) and push up?

**Comment by paulmarsicloud** [comment]
> @paulmarsicloud Here's a much more surgical hoisting allowance for the bad phantom dependency:
> 
> ```diff
> diff --git a/.npmrc b/.npmrc
> index c67cd2d..519f90d 100644
> --- a/.npmrc
> +++ b/.npmrc
> @@ -1,3 +1,5 @@
>  strict-peer-dependencies=false
>  prefer-workspace-packages=true
> -shamefully-hoist=true
> \ No newline at end of file
> +
> +# Docusaurus has some phantom dependencies, so specifically hoist those.
> +public-hoist-pattern[]=@docusaurus/theme-classic
> diff --git a/website/package.json b/website/package.json
> index 81a1b08..926a5e4 100644
> --- a/website/package.json
> +++ b/website/package.json
> @@ -12,8 +12,10 @@
>      "@docusaurus/preset-classic": "^2.0.1",
>      "@docusaurus/theme-live-codeblock": "^2.0.1",
>      "@docusaurus/theme-search-algolia": "^2.0.1",
> +    "@docusaurus/types": "^2.0.1",
>      "@mdx-js/react": "^1.6.22",
>      "@tsconfig/docusaurus": "^1.0.5",
> +    "@types/node": "^18.0.3",
>      "@types/styled-components": "^5.1.25",
>      "clsx": "^1.1.1",
>      "docusaurus-plugin-sass": "^0.2.2",
> ```
> 
> Want me to make a commit (alongside the pnpm-lock.yaml changes) and push up?

That makes sense, go for it!

**Review by gksander — APPROVED** [review]

**Comment by gksander** [comment]
@paulmarsicloud wanted to check in on this – how do you feel about merging this?

**Comment by paulmarsicloud** [comment]
> @paulmarsicloud wanted to check in on this – how do you feel about merging this?

works for me! we ok with 1 approval or shall I seek a second?

**Comment by gksander** [comment]
I think 1 will be alright for this!

**Pull request merged**
