### PR TITLE
gif support

### PR DESCRIPTION
**Pull request by WhoMeNope**

### CODE REVIEW

**Comment by manjula91** [comment]
Shouldn't we add svg as well

example:

`{
    test: /\.(jpe?g|png|gif|svg)$/i, 
    loader: "file-loader?name=/public/icons/[name].[ext]"
}`

**Comment by WhoMeNope** [comment]
@manjula91 svg files are already handled by their own rule

```javascript
{
    test: /\.(png|jpg|gif)$/,
    loader: 'url-loader?limit=8192',
},
{
    test: /\.svg$/,
    loader: 'url-loader?limit=10000&mimetype=image/svg+xml',
},
```

**Comment by rainboxx** [comment]
Travis should pass once #527 is merged and this branch rebased.

**Comment by rainboxx** [comment]
@WhoMeNope #527 is merged, could you rebase this so the checks are going through again? Thanks!

**Pull request merged**
