### PR TITLE
Enable prev and next slide with up and down keys

### PR DESCRIPTION
**Pull request by patrick91**
Shall I make this configurable somehow? Or is it fine as it is now?

### CODE REVIEW

**Comment by ryan-roemer** [comment]
@kenwheeler -- Where did we end up with the "2d matrix" idea of slides like reveal does it? (If we're still toying with that may want up/down to be saved for just within a column)

**Comment by patrick91** [comment]
@ryan-roemer I'd make it at least configurable if we have something like reveal :)

My [remote](https://www.amazon.co.uk/Doosl-DSIT001B-IT11-DSIT001/dp/B013W64932?ie=UTF8&psc=1&redirect=true&ref_=oh_aui_detailpage_o01_s00) has only up/down buttons :\

**Comment by kenwheeler** [comment]
I definitely want the 2d matrix at some point. That said, it would be cool to do an atom style key map config to support a variety of remotes.

**Comment by kenwheeler** [comment]
Electron style*

**Comment by patrick91** [comment]
@kenwheeler can you point me at some examples? I wasn't able to find anything.

**Comment by bebraw** [comment]
Maybe it would make sense to expose the keys through a `prop` while using the current defaults. You could also consider mapping strings to ASCII to make it easy to use.

👍  to reveal.js style slide sets. That would be awesome but also a separate PR.

**Comment by halhenke** [comment]
Glad i checked this PR - was thinking of taking a crack at the Reveal style grid as in #57 and was wondering how people would feel about the change in key bindings (in Reveal the left and right arrows switch between "stacks of slides" while up and down goes between slides/fragments). 

Making it configurable should make everyone happy.

**Comment by kenwheeler** [comment]
Closing in favor of a feature discussion regarding keymapping

**Pull request closed without merging**
